---
deployment:
  tasks:
    - export DEPLOYPATH=/home/allymapi/public_html/
    - /bin/cp -R dist/assets $DEPLOYPATH
    - /bin/cp -R dist/locales $DEPLOYPATH
    - /bin/cp -R dist/images $DEPLOYPATH
    - /bin/cp dist/.htaccess $DEPLOYPATH
    - /bin/cp dist/index.html $DEPLOYPATH
    - /bin/cp dist/manifest.webmanifest $DEPLOYPATH
    - /bin/cp dist/registerSW.js $DEPLOYPATH
    - /bin/cp dist/robots.txt $DEPLOYPATH
    - /bin/cp dist/sw.js $DEPLOYPATH
    - /bin/cp dist/workbox-3625d7b0.js $DEPLOYPATH
